# LTO_ENABLE = yes
# EXTRAKEY_ENABLE = yes
# # UNICODEMAP_ENABLE = yes
# # UNICODE_ENABLE = no
# # UCIS_ENABLE = no

# UNICODE_ENABLE = no
# UNICODEMAP_ENABLE = yes
#COMBO_ENABLE = yes
#CONSOLE_ENABLE = yes
